# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://cs.ubc.ca/~wsgh/
baseurl:
title: Will Harvey
author: Will Harvey
description: Personal website
avatar: profile.png
email: wsgh@cs.ubc.ca
github: wsgharvey
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
#exclude: [vendor] not using github pages
